FIX: sufficient check for error return code

diff --git a/bin/build-static-deployment b/bin/build-static-deployment
--- a/bin/build-static-deployment
+++ b/bin/build-static-deployment
@@ -54,12 +54,16 @@ esac
 
 echo "Exporting $APP"
 
+
 mkdir "$TARGET" \
     && rsync -vvap "$PROJECT/" "$TARGET/project/"\
     && cp "$SOURCE/README.md" "$TARGET" \
-    && cp "$SOURCE/LICENSE.txt" "$TARGET" \
-    || echo "ERROR: failed copying resources." \
-    && exit 1 ;
+    && cp "$SOURCE/LICENSE.txt" "$TARGET"
+
+if [ $? != 0 ]; then
+    echo "ERROR: failed copying resources."
+    exit 1
+fi;
 
 
 
